import React, { useMemo } from 'react';
import {
	Drawer,
	DrawerClose,
	DrawerContent,
	DrawerFooter,
	DrawerHeader,
	DrawerTitle,
	DrawerTrigger,
} from '@/components/ui/drawer';

import { Button } from '@/components/ui/button';
import ConfigSlider from './ConfigSlider';
import type { Config } from '@/types';

interface ConfigDrawerProps {
	config: Config;
	setConfig: React.Dispatch<React.SetStateAction<Config>>;
	defaultConfig: Config;
}

export default function ConfigDrawer({
	config,
	setConfig,
	defaultConfig,
}: ConfigDrawerProps) {
	const curriedUpdaters: Record<string, (value: number) => void> = useMemo(
		() =>
			Object.keys(defaultConfig).reduce(
				(acc, key) => {
					acc[key] = (value: number) => {
						setConfig((prev: Config) => ({
							...prev,
							[key]: value,
						}));
					};
					return acc;
				},
				{} as Record<string, (value: number) => void>
			),
		[defaultConfig, setConfig]
	);

	const { n_chunks, max_tokens, temperature, top_n_chunks } = config;

	return (
		<Drawer>
			<DrawerTrigger asChild>
				<Button className='w-full' variant='secondary'>
					Configurations
				</Button>
			</DrawerTrigger>

			<DrawerContent aria-describedby={undefined} className='p-3'>
				<DrawerHeader>
					<DrawerTitle className='text-lg'>
						Configurations
					</DrawerTitle>
				</DrawerHeader>
				<div className='mx-auto w-7xl p-2 space-y-12'>
					<ConfigSlider
						min={64}
						max={2048}
						step={32}
						label='Max Tokens'
						value={max_tokens}
						setValue={curriedUpdaters.max_tokens}
						defaultValue={defaultConfig.max_tokens}
						details='The maximum number of tokens that can be generated by the language model in a single response.'
					/>
					<ConfigSlider
						min={0}
						max={1}
						step={0.05}
						label='Temperature'
						value={temperature}
						setValue={curriedUpdaters.temperature}
						defaultValue={defaultConfig.temperature}
						details='The temperature value used during generation. Higher values are associated with more variability in generated text, while lower values often cause more consistent and coherent responses.'
					/>
					<ConfigSlider
						min={10}
						max={100}
						step={1}
						label='N Chunks'
						value={n_chunks}
						setValue={curriedUpdaters.n_chunks}
						defaultValue={defaultConfig.n_chunks}
						details='The initial number of chunks that are retrieved from the document database.'
					/>
					<ConfigSlider
						min={1}
						max={15}
						step={1}
						label='Top N Chunks'
						value={top_n_chunks}
						setValue={(v: number) => {
							if (v <= n_chunks) {
								curriedUpdaters.top_n_chunks(v);
							}
						}}
						defaultValue={defaultConfig.top_n_chunks}
						details='The number of top chunks fed to the generation model after the chunks retrieved initially are reranked based on the query.'
					/>
				</div>
				<DrawerFooter className='flex flex-row mx-auto p-6 gap-x-4 w-3xs'>
					<DrawerClose asChild>
						<Button variant='outline' className='w-1/2'>
							Cancel
						</Button>
					</DrawerClose>
					<Button
						onClick={() => setConfig(defaultConfig)}
						className='w-1/2'
					>
						Reset
					</Button>
				</DrawerFooter>
			</DrawerContent>
		</Drawer>
	);
}
